# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='requests.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0erequests.proto\"\x8b\x01\n\x08KeyTuple\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x1a\n\x12\x61\x64\x64ress_cache_size\x18\x05 \x01(\r\x12\x12\n\ninvalidate\x18\x06 \x01(\x08\x12\x11\n\taddresses\x18\x07 \x03(\t\"q\n\nKeyRequest\x12\x1a\n\x04type\x18\x01 \x02(\x0e\x32\x0c.RequestType\x12\x19\n\x06tuples\x18\x02 \x03(\x0b\x32\t.KeyTuple\x12\x18\n\x10response_address\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"=\n\x0bKeyResponse\x12\x19\n\x06tuples\x18\x01 \x03(\x0b\x32\t.KeyTuple\x12\x13\n\x0bresponse_id\x18\x02 \x01(\t\"O\n\x11KeyAddressRequest\x12\x18\n\x10response_address\x18\x01 \x02(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"\x93\x01\n\x12KeyAddressResponse\x12\x31\n\taddresses\x18\x01 \x03(\x0b\x32\x1e.KeyAddressResponse.KeyAddress\x12\r\n\x05\x65rror\x18\x02 \x02(\r\x12\x13\n\x0bresponse_id\x18\x03 \x01(\t\x1a&\n\nKeyAddress\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0b\n\x03ips\x18\x02 \x03(\t*\x1f\n\x0bRequestType\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03PUT\x10\x01')
)

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=569,
  serialized_end=600,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
GET = 0
PUT = 1



_KEYTUPLE = _descriptor.Descriptor(
  name='KeyTuple',
  full_name='KeyTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyTuple.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='KeyTuple.error', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='KeyTuple.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='KeyTuple.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_cache_size', full_name='KeyTuple.address_cache_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invalidate', full_name='KeyTuple.invalidate', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='KeyTuple.addresses', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=158,
)


_KEYREQUEST = _descriptor.Descriptor(
  name='KeyRequest',
  full_name='KeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='KeyRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tuples', full_name='KeyRequest.tuples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_address', full_name='KeyRequest.response_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='KeyRequest.request_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=273,
)


_KEYRESPONSE = _descriptor.Descriptor(
  name='KeyResponse',
  full_name='KeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tuples', full_name='KeyResponse.tuples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_id', full_name='KeyResponse.response_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=336,
)


_KEYADDRESSREQUEST = _descriptor.Descriptor(
  name='KeyAddressRequest',
  full_name='KeyAddressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_address', full_name='KeyAddressRequest.response_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keys', full_name='KeyAddressRequest.keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='KeyAddressRequest.request_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=417,
)


_KEYADDRESSRESPONSE_KEYADDRESS = _descriptor.Descriptor(
  name='KeyAddress',
  full_name='KeyAddressResponse.KeyAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyAddressResponse.KeyAddress.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ips', full_name='KeyAddressResponse.KeyAddress.ips', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=567,
)

_KEYADDRESSRESPONSE = _descriptor.Descriptor(
  name='KeyAddressResponse',
  full_name='KeyAddressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='KeyAddressResponse.addresses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='KeyAddressResponse.error', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_id', full_name='KeyAddressResponse.response_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_KEYADDRESSRESPONSE_KEYADDRESS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=567,
)

_KEYREQUEST.fields_by_name['type'].enum_type = _REQUESTTYPE
_KEYREQUEST.fields_by_name['tuples'].message_type = _KEYTUPLE
_KEYRESPONSE.fields_by_name['tuples'].message_type = _KEYTUPLE
_KEYADDRESSRESPONSE_KEYADDRESS.containing_type = _KEYADDRESSRESPONSE
_KEYADDRESSRESPONSE.fields_by_name['addresses'].message_type = _KEYADDRESSRESPONSE_KEYADDRESS
DESCRIPTOR.message_types_by_name['KeyTuple'] = _KEYTUPLE
DESCRIPTOR.message_types_by_name['KeyRequest'] = _KEYREQUEST
DESCRIPTOR.message_types_by_name['KeyResponse'] = _KEYRESPONSE
DESCRIPTOR.message_types_by_name['KeyAddressRequest'] = _KEYADDRESSREQUEST
DESCRIPTOR.message_types_by_name['KeyAddressResponse'] = _KEYADDRESSRESPONSE
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyTuple = _reflection.GeneratedProtocolMessageType('KeyTuple', (_message.Message,), dict(
  DESCRIPTOR = _KEYTUPLE,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:KeyTuple)
  ))
_sym_db.RegisterMessage(KeyTuple)

KeyRequest = _reflection.GeneratedProtocolMessageType('KeyRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:KeyRequest)
  ))
_sym_db.RegisterMessage(KeyRequest)

KeyResponse = _reflection.GeneratedProtocolMessageType('KeyResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYRESPONSE,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:KeyResponse)
  ))
_sym_db.RegisterMessage(KeyResponse)

KeyAddressRequest = _reflection.GeneratedProtocolMessageType('KeyAddressRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYADDRESSREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:KeyAddressRequest)
  ))
_sym_db.RegisterMessage(KeyAddressRequest)

KeyAddressResponse = _reflection.GeneratedProtocolMessageType('KeyAddressResponse', (_message.Message,), dict(

  KeyAddress = _reflection.GeneratedProtocolMessageType('KeyAddress', (_message.Message,), dict(
    DESCRIPTOR = _KEYADDRESSRESPONSE_KEYADDRESS,
    __module__ = 'requests_pb2'
    # @@protoc_insertion_point(class_scope:KeyAddressResponse.KeyAddress)
    ))
  ,
  DESCRIPTOR = _KEYADDRESSRESPONSE,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:KeyAddressResponse)
  ))
_sym_db.RegisterMessage(KeyAddressResponse)
_sym_db.RegisterMessage(KeyAddressResponse.KeyAddress)


# @@protoc_insertion_point(module_scope)
